### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by silkyclouds** [Jorre05/micronova#1]
Hi and thank you for this super promising module ! 

I try to get thisto compile, but I end up getting missing files errors. 

Here is the content of my micronova.yaml file : 

````
name: micronova
  platform: ESP8266
  board: d1_mini
 
uart:
  id: uart_bus
  baud_rate: 1200
  data_bits: 8
  stop_bits: 2
  parity: NONE
  rx_pin: GPIO3
  tx_pin: GPIO4
 
external_components:
  - source: github://Jorre05/micronova
    components: [micronova]
 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.3.66
    gateway: 192.168.3.1
    subnet: 255.255.255.0
  ap:
    ssid: "micronova"
    password: "1234567890"
 
micronova:
  enable_rx_pin: 3
  update_interval: 5s
  scan_memory_location: 0x00
  room_temperature:
    memory_address: 0x01
    name: Ambient temperature
    id: ambient_temperature
  thermostat_temperature:
    name: Stove thermostat temperature
  fumes_temperature:
    name: Smoke temperature
  stove_power:
    name: Stove current power
  fan_speed:
    fan_rpm_offset: 240
    name: Fan RPM
    id: fan_rpm
  memory_address_sensor:
    memory_location: 0x20
    memory_address: 0x7d
    name: Memory Address sensor
    id: mem_address_sensor
  stove_state:
    memory_address: 0x21
    name: Stove Status
  stove_switch:
    memory_location: 0x80
    memory_address: 0x21
    memory_data_on: 0x01
    memory_data_off: 0x06
    name: Switch stove on/off
  but_temp_up:
    name: Increase thermostat
    memory_location: 0xA0
    memory_address: 0x7D
    memory_data: 0x21
  but_temp_down:
    name: Decrease thermostat
````

And here is the error I'm getting : 

````
In file included from src/esphome/components/micronova/micronova.cpp:1:
src/esphome/components/micronova/micronova.h:4:10: fatal error: esphome/components/sensor/sensor.h: No such file or directory
    4 | #include "esphome/components/sensor/sensor.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pioenvs/micronova/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
*** [.pioenvs/micronova/src/esphome/components/micronova/micronova.cpp.o] Error 1
````

If I create an empty section in the yaml called sensor, the compilation will fail at the next dependency "sensor_text" and if I add "sensor_text:" to the yaml, it will then fail at the next one called "switch" and so on. 

MAy I ask you what I am doing wrong here ? I really want to get this to work. :) 

thanks !
