### ISSUE TITLE
Adjusting the addresses of sensors or switches

### ISSUE THREAD

**Issue by geraldFS** [Jorre05/micronova#12]
Hello,

is there a way to manually influence the addresses of the sensors?

For example, I have a different address for the flue gas
fumesTempAddr = 0x5A

How can I create additional sensors?
Addresses are known.

**Comment by ricardocb** [comment]
Hi,

In the documentation, is there that you can create :

 memory_address_sensor:
      memory_location: 0x20
      memory_address: 0x7d
      name: Custom Adres sensor 

In the Name you can define a custom name.

Also the property memory_location and memory_address can be defined for any sensor that you use, like this:

sensor:
  - platform: micronova
    room_temperature:
      memory_location: 0xff
      memory_address: 0xee
      name: Room temperature

**Comment by geraldFS** [comment]
Since my oven has significantly more sensors, I would like to create several, not just one, one works but how can I create four additional sensors - head scratching

**Comment by ricardocb** [comment]
Hi!

I think the cod doesn't support that...
I only supports on "custom sensor".

I want to do the same think in my spare time, so  check my fork in the
future - If I have spare time maybe i will push something ther....

RP

Gerald ***@***.***> escreveu (sexta, 29/11/2024 à(s) 14:36):

**Comment by Jorre05** [comment]
Yes, for now, only one memory_address_sensor is allowed. If I find some time I'll update the code to allow multiple sensors

**Comment by Jorre05** [comment]
To have multiple  sensors you must make mutiple platform entries:

```yaml
sensor:
  - platform: micronova
    memory_address_sensor:
      name: "Address 0x5A"
      id: c1_id
      memory_location: 0x00
      memory_address: 0x5A
  - platform: micronova
    memory_address_sensor:
      name: "Address 0x34"
      id: c2_id
      memory_location: 0x00
      memory_address: 0x34
    room_temperature:
      name: Roomtemperature
      id: roomtemperature
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 20
            send_every: 1
            send_first_at: 1
```

**Comment by geraldFS** [comment]
Sorry - unfortunately it doesn't work like that.

Here is my code:

``sensor:
  - platform: micronova
    room_temperature:
      name: Raumtemperatur
    fumes_temperature:
      name: Abgastemperatur
      memory_location: 0x00
      memory_address: 0x5A
 
    stove_power:
      name: Leistung
    fan_speed:
      fan_rpm_offset: 240
      name: Abgaslüfter
    water_temperature:
      name: Wassertemperatur
      memory_location: 0x00
      memory_address: 0x03
      filters:
        - lambda: |-
           return x * 2;
    water_pressure:
      name: Wasserdruck
   
   - platform: micronova
     memory_address_sensor: 
       id: luefter1  
       memory_location: 0x00
       memory_address: 0x0a   
       name: Lüfter Warmluft1
       filters:
         - lambda: |-
            return x * 2;

   - platform: micronova
     memory_address_sensor: 
       id: luefter2  
       memory_location: 0x00
       memory_address: 0x0a   
       name: Lüfter Warmluft2
```


And here is the response when compiling:

```
INFO ESPHome 2024.11.3
INFO Reading configuration /config/esphome/wohnzimmerofen.yaml...
ERROR Error while reading config: Invalid YAML syntax:

while parsing a block collection
  in "/config/esphome/wohnzimmerofen.yaml", line 123, column 3
expected <block end>, but found '<block sequence start>'
  in "/config/esphome/wohnzimmerofen.yaml", line 146, column 4
```

**Comment by Jorre05** [comment]
Must be some formatting syntax issue in your yaml I think. Could you try with a minimal working config?

**Comment by geraldFS** [comment]
So my control basically works.
As soon as I want to set up two memory_address_sensors the compiler complains.

In my opinion the syntax should look like this:
```
sensor:
- platform: micronova
  room_temperature:
  name: room temperature

  fumes_temperature:
  name: exhaust gas temperature
  memory_location: 0x00
  memory_address: 0x5A
  memory_address_sensor:
  id: example1
  memory_location: 0x00
  memory_address: 0x0a
  name: example1
```

up to that point the syntax works, but as soon as the second memory_address_sensor is inserted it's over.

I think that's where the error lies.
