### ISSUE TITLE
UART Errors

### ISSUE THREAD

**Issue by dackerman38** [Jorre05/micronova#14]
Hello

I have an issue with the project
the reading doesnt work, I always get the`[E][uart:015]: Reading from UART timed out at byte 0!` error.

I've tried with 2 different d1 minis, one with micro-usb and one with USB-C, I also tried with an ESP32 S2 mini
Always the same error. I have tried specifying `UARTO` and `framework:
    type: esp-idf` abd still the same error.
In the other hand writing is good, I can start the stove, shut it down, control power with the custom button.

any ideas please?

**Comment by tehkillerbee** [comment]
What circuit are you using to connect to the oven?

**Comment by dackerman38** [comment]
I'm using Philibert's pcb. But I get the errors even when the wemos isnt
connected to the pcb or the oven

Le mar. 21 janv. 2025, 20:31, Johannes L ***@***.***> a
écrit :

**Comment by Jorre05** [comment]
If the write works, but not the read, then probably there is something wrong with the interfacing hardware. A reversed optocoupler?

**Comment by dackerman38** [comment]
I have checked and the wiring seems to be good. I have the errors after a fresh install of the yaml and even before connecting to the board

**Comment by Jorre05** [comment]
You can flash you device with test code that exposes the TX and RX-enable as a switch and the RX as a sensor. When you then, without the stove connected, check the voltages on the TX en RX-enable lines you should see the voltage go up/down. Same when you apply 5V to the RX line, the sensor in Home Assistant should light up.

The yaml below is an example, you will need to adjust the pins for your board.

```yaml
switch:
  - platform: gpio
    name: "TX test"
    id: tx_test
    pin: 5
  - platform: gpio
    name: "Enable RX test"
    id: enable_rx_test
    pin: 7

binary_sensor:
  - platform: gpio
    name: "RX test sensor"
    id: rx_test
    pin: 4
```
