### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by pippo93** [Jorre05/micronova#8]
Hi,
I’m having some trouble to compile this component in a Wemos D1 Mini for my pellet stove.
Both “number:” and “switch:” part of code are ok, but “sensor:” part always fail with a error saying something like “unable to fine micronova.sensor”.

The code i’m trying to use is:
```
sensor:
  - platform: micronova
    room_temperature:
      name: Temperatura Stanza
    fumes_temperature:
      name: Temperatura Fumi
```
as reported on this github page. Can anyone help me? Thx
